### ISSUE TITLE
PYTHON_EXECUTABLE requires absolute path

### ISSUE THREAD

**Issue by timonegk** [stack-of-tasks/eigenpy-ros-release#1]
I am building ROS Noetic on Debian Testing and experienced the following problem while building:
```
CMake Error at cmake/python.cmake:77 (MESSAGE):
  python3 is not a valid path to the Python executable
```
The issue seems to be in `CMakeLists.txt:21`, where `PYTHON_EXECUTABLE` is set to `python3`. It works for me if `python3` is changed to `/usr/bin/python3`.

**Comment by wxmerkt** [comment]
Hi @timonegk,
Sorry to hear you are having issues building. Can you confirm which release you are using and if you are installing the sources from deb-src?

I believe you are referring to the patch in https://github.com/ipab-slmc/eigenpy_catkin-release/blob/patches/release/noetic/eigenpy/0004-Explicitly-set-Python3-for-Debian-Buster.patch. I haven't received a failure email from the buildfarm (yet?) so thought this would work. Happy to change it and re-release.

**Comment by timonegk** [comment]
I am installing from the [latest tar archive](https://github.com/ipab-slmc/eigenpy_catkin-release/archive/release/noetic/eigenpy/2.6.1-1.tar.gz) which I obtained via `rosinstall_generator`. I am building from source from the tar archive (basically following [this guide](https://wiki.ros.org/Installation/Source)) and not using any debian packages.

The line in question seems to be coming from the patch you linked, yes. I assume the build farm only tests Debian Buster/Stable and not Testing which might have newer packages that require the change. But I am certain that setting `PYTHON_EXECUTABLE` to the full path would be correct because in `cmake/python.cmake`, `IF(NOT EXISTS ${PYTHON_EXECUTABLE})` is used and according to the [cmake documentation](https://cmake.org/cmake/help/latest/command/if.html), `EXISTS` is only well-defined for full paths.

**Comment by wxmerkt** [comment]
Thank you for the detailed report. Can you please try again with https://github.com/ipab-slmc/eigenpy_catkin-release/archive/release/noetic/eigenpy/2.6.1-3.tar.gz?

I've also opened a PR with the release to the buildfarm: https://github.com/ros/rosdistro/pull/28136

**Comment by timonegk** [comment]
Thank you for the quick reaction, it works fine with the new release!
