### ISSUE TITLE
python3_add_library ignores CMAKE_DEBUG_POSTFIX 

### ISSUE THREAD

**Issue by aosadchenko-alst** [stack-of-tasks/eigenpy-ros-release#3]
If I set CMAKE_DEBUG_POSTFIX , my module(c++ shared library) fails to add  to pyhton 

without it 'python3_add_library(bla MODULE bla.cpp)' works just fine , but with CMAKE_DEBUG_POSTFIX set to 'dbg' it fails to load it

**Comment by aosadchenko-alst** [comment]
I also tied $<TARGET_FILE_NAME:bla>, it does not even parse

**Comment by wxmerkt** [comment]
Hi @aosadchenko-alst 
I need a little more information to help provide input or insights. Is this only happening when installing EigenPy via the ROS buildfarm released versions (`ros-[melodic/noetic]-eigenpy`) or is this also happening with EigenPy installed from source?

What is your setup (environment, CMake file etc.) and what is the failure?

**Comment by wxmerkt** [comment]
Closing until further information received
