### ISSUE TITLE
How to install eigenpy?

### ISSUE THREAD

**Issue by dazhongtu** [stack-of-tasks/eigenpy-ros-release#5]
I have already installed eigenpy manually ,following https://github.com/stack-of-tasks/eigenpy.
However, when I tried pinocchio in ROS melodic, terminal shows 
"
CMake Error at /opt/ros/melodic/share/cmake/pinocchio/pinocchioConfig.cmake:150 (find_package):
  Could not find a configuration file for package "eigenpy" that is
  compatible with requested version "2.7.10".

  The following configuration files were considered but not accepted:

    /opt/ros/melodic/share/eigenpy/cmake/eigenpyConfig.cmake, version: 2.7.5

Call Stack (most recent call first):
  control_algorithm/CMakeLists.txt:210 (find_package
"
Then I saw your github and I tried this command "eigenpymelodic/usr/bin/bloom-release -r melodic --non-interactive eigenpy"
Another error occured,it shows
"==> git push --dry-run
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Cannot push to remote release repository.
Hint: If you just typed in your username/password and you have two-factor authentication,see:
  [http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization](https://link.zhihu.com/?target=http%3A//wiki.ros.org/bloom/Tutorials/GithubManualAuthorization)"
  What should I do ?
  I would appreciate it if you could answer me

**Comment by wxmerkt** [comment]
Hi @dazhongtu,
This is the release repository which you should not be using. I assume that you ran `sudo apt-get install ros-melodic-eigenpy`. The current version of EigenPy in ROS Melodic is 2.9.2. Can you try `sudo apt-get update && sudo apt-get install ros-melodic-eigenpy` to install the latest version? This should fix your problem
